/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop.glb -t
Author: FishyBusiness (https://sketchfab.com/FishyBusiness)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-5445f813654e41758db959cf07a5532a
Title: Laptop
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
  };
  materials: {
    ['laptop_top.png']: THREE.MeshStandardMaterial;
    ['laptop_topscreen.png']: THREE.MeshPhysicalMaterial;
    ['laptop_keyboard.png']: THREE.MeshStandardMaterial;
    ['laptop_keyboardbottom.png']: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./src/assets/laptop.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.25} rotation={[0.3, 2.9, 0]}>
      {/* <group position={[15.95, 0, 18.79]} rotation={[-Math.PI / 2, 0, 3.14]}> */}
      {/* <group rotation={[Math.PI / 2, 0, 0]}> */}
      <group position={[0, -3, 2]} rotation={[Math.PI / 8, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['laptop_topscreen.png']} />
      </group>
      <group position={[3, 4, 0]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['laptop_keyboardbottom.png']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['laptop_keyboard.png']} />
      </group>
      {/* </group> */}
      {/* </group> */}
    </group>
  );
}

useGLTF.preload('./src/assets/laptop.glb');
