/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('./src/assets/source/model.gltf');
  return (
    <group {...props} dispose={null} scale={0.25} rotation={[0.3, 2.9, 0]}>
      <group position={[0, -3, 2]} rotation={[Math.PI / 8, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={materials['laptop_top.png']} />
        <mesh geometry={nodes.mesh_0_5.geometry} material={materials['laptop_topscreen.png']} />
      </group>
      <group position={[3, 4, 0]}>
        <mesh geometry={nodes.mesh_1.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.mesh_1_1.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.mesh_1_2.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.mesh_1_3.geometry} material={materials['laptop_keyboardbottom.png']} />
        <mesh geometry={nodes.mesh_1_4.geometry} material={materials['laptop_keyboard.png']} />
        <mesh geometry={nodes.mesh_1_5.geometry} material={materials['laptop_keyboard.png']} />
      </group>
    </group>
  );
}

useGLTF.preload('./src/assets/source/model.gltf');
